CREATE TABLE [dbo].[Item] (
    [Id] BIGINT IDENTITY(1,1)  NOT NULL,
    CONSTRAINT PK_ItemId PRIMARY KEY CLUSTERED (Id),
    [Name] VARCHAR  (200) NOT NULL,
    [Description] VARCHAR (300) NULL,
    [Price] SMALLINT  NOT NULL,
    [Stock] SMALLINT  NOT NULL,
    [ItemImage] VARCHAR(500) NULL
);

